doctrine:
    dbal:
        default_connection: MONTERREY
        connections:
            MONTERREY:
                # driver: 'pdo_sqlsrv'
                # host: 'localhost'
                # port: 1433
                # dbname: 'CRM360'
                # user: 'sa'
                # password: '123'
                # charset: 'UTF-8'
                driver: "pdo_sqlsrv"
                host: '192.168.0.113\CRM360'
                port: 51817
                dbname: 'CRM360'
                user: 'sa'
                password: '123'
                charset: "UTF-8"
    # orm:
    #     auto_generate_proxy_classes: true
    #     naming_strategy: doctrine.orm.naming_strategy.underscore
    #     auto_mapping: true
    #     mappings:
    #         App:
    #             is_bundle: false
    #             type: annotation
    #             dir: '%kernel.project_dir%/src/Entity'
    #             prefix: 'App\Entity'
    #             alias: App
