doctrine:
    dbal:
        default_connection: MONTERREY
        connections:
            MONTERREY:
                # driver: 'pdo_sqlsrv'
                # host: 'SDMTSQL01\DMANETONI'
                # port: 60040
                # dbname: 'MTCORP'
                # user: 'appMTCorp'
                # password: 'appMTCorp'
                # charset: 'UTF-8'
                # driver: "pdo_sqlsrv"
                # host: '10.130.10.52\DMTCORP'
                # port: 49179
                # dbname: "MONTERREY"
                # user: "appIMTCorp"
                # password: "appIMTCorpDEV"
                # charset: "UTF-8"
<<<<<<< HEAD
                  host: 127.0.0.1
                  port: 1433       
                  dbname: 'CRM360'
                  user: 'reflo'
                  password: '123'
=======
                  driver: 'pdo_sqlsrv'
                  host: 'localhost'
                  port: 1433
                  dbname: 'CRM360'
                  user: 'diego'
                  password: 'diego123'
>>>>>>> 48dc5dcb056792439776f2bf6ecc8d4f1558d52c
                  charset: 'UTF-8'
    # orm:# 
    #     auto_generate_proxy_classes: true
    #     naming_strategy: doctrine.orm.naming_strategy.underscore
    #     auto_mapping: true
    #     mappings:
    #         App:
    #             is_bundle: false
    #             type: annotation
    #             dir: '%kernel.project_dir%/src/Entity'
    #             prefix: 'App\Entity'
    #             alias: App
