api.home:
    path: /
    methods: [GET]
    controller: App\Controller\Core\HomeController::home

api.usuario.login:
    path: /usuario/login
    methods: [POST]
    controller: App\Controller\Core\LoginController::login
